package com.borinquenterrier.cef

// HARD-6 (ROADMAP.md Phase 10): isDebug previously defaulted to true unless a `debug` system
// property or DEBUG env var was explicitly set to "false" — but nothing in release-desktop.yml
// or build.gradle.kts ever set that, so a packaged .dmg/.msi/.deb shipped in debug mode (unbounded
// debug_logs.txt growth included) by default. IS_PACKAGED_DESKTOP_RELEASE is generated by the
// generateJvmBuildFlags Gradle task from the actual task graph (true only when a packageRelease*
// task is running), so a release can no longer ship debug-on just because nobody remembered to
// set an env var. Takes explicit params (rather than reading System.getenv/getProperty directly)
// so the gating logic itself is unit-testable without touching real process state.
internal fun computeIsDebug(
    isPackagedRelease: Boolean,
    debugSystemProperty: String?,
    debugEnvVar: String?,
): Boolean = !isPackagedRelease && debugSystemProperty != "false" && debugEnvVar != "false"
